name: Rain Alert

on:
  schedule:
    - cron: "0 7 * * *"

  workflow_dispatch:


jobs:
  rain-check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run rain alert script
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

        run: |
          python main.py